username: satyam8306
password: {secret.PASSWORD}
phone_number: {secret.PHONE}

positions:
  - AI Intern
  - Machine Learning Intern
  - Data Science Intern
  - Deep Learning Intern
  - Gen AI Intern

locations:
  - Remote
  - Bangalore, India
  - Hyderabad, India

salary: 0  # Set to 0 if not applicable or if you're open to unpaid internships
rate: 0    # Set to 0 if not applicable

uploads:
  Resume: data\newResume.pdf
  Cover Letter: data\newResume.pdf
  Photo: data\profile_photo.jpg
  # Note: Ensure the file paths are correct and accessible

output_filename:
  - output.csv  

blacklist:
  - Company A
  - Company B
  # Add any companies you wish to exclude from applications


experience_level:
  - 1 Entry level
  - 2 Associate
  - 3 Mid-Senior level
  - 4 Director
  - 5 Executive
  - 6 Internship